# Generated by Django 2.1.7 on 2019-12-10 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Chart',
                'verbose_name_plural': 'Chart',
                'db_table': 'Chart',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('birthday', models.DateField()),
                ('gender', models.BooleanField()),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('reg_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Customers',
                'verbose_name_plural': 'Customers',
                'db_table': 'Customers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('final_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Deals',
                'verbose_name_plural': 'Deals',
                'db_table': 'Deals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('cabinet', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Departments',
                'verbose_name_plural': 'Departments',
                'db_table': 'Departments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('birthday', models.DateField()),
                ('gender', models.BooleanField()),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('position', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('reg_date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Departments')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee',
                'db_table': 'Employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Customers')),
                ('employee', models.ManyToManyField(to='website.Employee')),
            ],
            options={
                'verbose_name': 'Requests',
                'verbose_name_plural': 'Requests',
                'db_table': 'Requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('internet', 'internet'), ('outdoor', 'outdoor'), ('indoor', 'indoor'), ('transport', 'transport'), ('media', 'media'), ('polygraphy', 'polygraphy')], max_length=50)),
                ('types', models.CharField(choices=[('targeting', 'targeting'), ('banners', 'banners'), ('instagram', 'instagram'), ('youtube', 'youtube'), ('website', 'website'), ('arch', 'arch'), ('poster', 'poster'), ('backlight', 'backlight'), ('billboard', 'billboard'), ('citylight', 'citylight'), ('scroll', 'scroll'), ('university', 'university'), ('shopping center', 'shopping center'), ('cinema', 'cinema'), ('elevator', 'elevator'), ('parking', 'parking'), ('bus', 'bus'), ('trolleybus', 'trolleybus'), ('tram', 'tram'), ('autobrending', 'autobrending'), ('train', 'train'), ('tv', 'tv'), ('radio', 'radio'), ('video', 'video'), ('photo', 'photo'), ('newspaper', 'newspaper'), ('flyer', 'flyer'), ('bussiness card', 'bussiness card'), ('sticker', 'sticker'), ('calendar', 'calendar')], max_length=50)),
                ('description', models.CharField(max_length=256)),
                ('picture', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=13)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Departments')),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
                'db_table': 'Services',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='deals',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Requests'),
        ),
        migrations.AddField(
            model_name='deals',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Services'),
        ),
        migrations.AddField(
            model_name='chart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Customers'),
        ),
        migrations.AddField(
            model_name='chart',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Services'),
        ),
    ]
