# Generated by Django 2.1.7 on 2020-05-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='username',
            field=models.CharField(default=111111, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
