# Generated by Django 2.1.7 on 2020-05-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200510_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default=11111, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
