# Generated by Django 2.1.7 on 2020-05-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_employee_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
