# Generated by Django 2.1.7 on 2020-05-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200510_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='login',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='username',
            new_name='login',
        ),
    ]
