# Generated by Django 2.1.7 on 2020-05-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200510_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='login',
        ),
    ]
