# Generated by Django 2.1.7 on 2020-05-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='gender',
            field=models.CharField(choices=[('male', 'мужской'), ('female', 'женский')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'мужской'), ('female', 'женский')], max_length=15, null=True),
        ),
    ]
