# Generated by Django 2.1.7 on 2020-05-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20200510_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'мужской'), ('female', 'женский')], default='male', max_length=15),
        ),
    ]
