# Generated by Django 2.1.7 on 2020-05-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200511_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deals',
            name='final_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='deals',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
