# Generated by Django 2.1.7 on 2020-05-12 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20200512_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Employee'),
        ),
    ]
