# Generated by Django 2.1.7 on 2020-05-12 22:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20200512_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='birthday',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0, 0, 0), null=True),
        ),
    ]
